import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Keyboard, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { Image } from 'expo-image';
import * as Haptics from 'expo-haptics';
import { supabase } from '@/lib/supabase';
import { palette, radii } from '@/lib/theme';
import { StatusCard } from '@/components/status-card';

type ScannerOption = { id: string; manufacturer: string; model: string; field_strength_t: number };
type ScannerProfile = ScannerOption & { nickname?: string | null; is_default?: boolean; generic_scanner_model_id?: string | null };
type DeviceOption = { id: string; manufacturer?: string; model?: string; family?: string; device_type?: string };
type ComponentOption = { id: string; model?: string; component_type?: string };
type SelectedComponent = ComponentOption & { slot: string };

function SectionTitle({ step, title, detail }: { step: string; title: string; detail: string }) {
  return <View style={{ gap: 4 }}><Text style={{ color: palette.brand, fontSize: 12, fontWeight: '800' }}>{step}</Text><Text style={{ color: palette.text, fontSize: 21, fontWeight: '800' }}>{title}</Text><Text style={{ color: palette.muted, fontSize: 14, lineHeight: 20 }}>{detail}</Text></View>;
}

function SearchField({ value, onChangeText, placeholder, onSubmit }: { value: string; onChangeText: (v:string)=>void; placeholder:string; onSubmit:()=>void }) {
  return <View style={{ flexDirection:'row', alignItems:'center', gap:10, backgroundColor:palette.surface, borderWidth:1, borderColor:palette.line, borderRadius:radii.md, paddingHorizontal:14 }}><Image source="sf:magnifyingglass" style={{width:18,height:18}} tintColor={palette.muted}/><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={palette.muted} returnKeyType="search" onSubmitEditing={()=>{Keyboard.dismiss();onSubmit();}} style={{flex:1,height:50,color:palette.text,fontSize:16}}/></View>;
}

export default function QuickCheckScreen() {
  const [profiles,setProfiles]=useState<ScannerProfile[]>([]); const [scanner,setScanner]=useState<ScannerOption|null>(null); const [scannerProfileId,setScannerProfileId]=useState<string|null>(null);
  const [showScannerPicker,setShowScannerPicker]=useState(false); const [deviceSearch,setDeviceSearch]=useState(''); const [devices,setDevices]=useState<DeviceOption[]>([]); const [device,setDevice]=useState<DeviceOption|null>(null);
  const [componentSearch,setComponentSearch]=useState(''); const [components,setComponents]=useState<ComponentOption[]>([]); const [selectedComponents,setSelectedComponents]=useState<SelectedComponent[]>([]);
  const [scanRegion,setScanRegion]=useState('full body'); const [serialNumber,setSerialNumber]=useState(''); const [result,setResult]=useState<any>(null); const [busy,setBusy]=useState(false);

  useEffect(()=>{(async()=>{const {data}=await supabase.rpc('quickcheck_list_scanner_profiles'); const rows=(data??[]) as ScannerProfile[]; setProfiles(rows); const d=rows.find(x=>x.is_default); if(d){setScanner({id:d.generic_scanner_model_id||d.id,manufacturer:d.manufacturer,model:d.model,field_strength_t:d.field_strength_t});setScannerProfileId(d.id);}})();},[]);
  const tone=useMemo(()=>result?.status==='safe'?'safe':result?.status==='conditional'||result?.status==='guidance'?'conditional':result?.status==='unsafe'||result?.status==='not_cleared'?'danger':'unknown',[result]);

  async function searchDevices(){Keyboard.dismiss();setBusy(true);const {data,error}=await supabase.rpc('quickcheck_search_devices',{p_search:deviceSearch.trim()});setBusy(false);if(error)return setResult({status:'unknown',display_status:'DEVICE SEARCH ERROR',decision:error.message});setDevices(((data??[]) as DeviceOption[]).slice(0,20));}
  async function searchComponents(){Keyboard.dismiss();if(!device)return;setBusy(true);const {data,error}=await supabase.rpc('quickcheck_search_components',{p_device_id:device.id,p_search:componentSearch.trim()});setBusy(false);if(error)return setResult({status:'unknown',display_status:'COMPONENT SEARCH ERROR',decision:error.message});setComponents(((data??[]) as ComponentOption[]).slice(0,30));}
  function chooseProfile(p:ScannerProfile){setScanner({id:p.generic_scanner_model_id||p.id,manufacturer:p.manufacturer,model:p.model,field_strength_t:p.field_strength_t});setScannerProfileId(p.id);setShowScannerPicker(false);setResult(null);}
  async function runCheck(){Keyboard.dismiss();if(!device)return;setBusy(true);await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);let response:any;if(scanner&&selectedComponents.length){response=await supabase.rpc('quickcheck_run_exact_system_check_v3',{p_device_id:device.id,p_components:selectedComponents.map((x,i)=>({component_id:x.id,slot:x.slot.trim()||`component_${i+1}`})),p_scanner_model_id:scanner.id,p_scanner_strength_t:scanner.field_strength_t,p_scan_region:scanRegion,p_generator_serial_number:serialNumber.trim()||null,p_implant_metadata: scannerProfileId?{scanner_profile_id:scannerProfileId}:{}});}else{response=await supabase.rpc('quickcheck_get_device_guidance',{p_device_id:device.id,p_scanner_strength_t:scanner?.field_strength_t??null,p_scan_region:scanRegion.trim()||null});}setBusy(false);setResult(response.error?{status:'unknown',display_status:'QUICKCHECK ERROR',decision:response.error.message}:response.data);}

  return <ScrollView contentInsetAdjustmentBehavior="automatic" keyboardDismissMode="interactive" keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:16,paddingBottom:60,gap:22}}>
    <SectionTitle step="OPTIONAL" title="Your scanner" detail="Your default saved scanner is selected automatically. Change it or choose Scanner unknown for manufacturer-guidance-only lookup."/>
    <Pressable onPress={()=>setShowScannerPicker(v=>!v)} style={{backgroundColor:palette.surface,borderWidth:1.5,borderColor:scanner?palette.brand:palette.line,borderRadius:radii.md,padding:15,flexDirection:'row',alignItems:'center',gap:12}}><Image source="sf:wave.3.right.circle.fill" style={{width:25,height:25}} tintColor={palette.brand}/><View style={{flex:1,gap:2}}><Text style={{color:palette.text,fontWeight:'800',fontSize:16}}>{scanner?`${scanner.manufacturer} ${scanner.model}`:'Scanner unknown / guidelines only'}</Text><Text style={{color:palette.muted,fontSize:13}}>{scanner?`${scanner.field_strength_t}T · Saved scanner`:'No scanner-specific compatibility determination'}</Text></View><Text style={{color:palette.brand,fontWeight:'900'}}>Change</Text></Pressable>
    {showScannerPicker?<View style={{gap:8}}><Pressable onPress={()=>{setScanner(null);setScannerProfileId(null);setShowScannerPicker(false);}} style={{padding:14,borderRadius:radii.md,borderWidth:1,borderColor:palette.line,backgroundColor:palette.surface}}><Text style={{color:palette.text,fontWeight:'800'}}>Scanner unknown / guidelines only</Text><Text style={{color:palette.muted,fontSize:12}}>Do not filter guidance by scanner strength</Text></Pressable>{profiles.map(p=><Pressable key={p.id} onPress={()=>chooseProfile(p)} style={{padding:14,borderRadius:radii.md,borderWidth:1,borderColor:p.id===scannerProfileId?palette.brand:palette.line,backgroundColor:p.id===scannerProfileId?palette.brandSoft:palette.surface}}><Text style={{color:palette.text,fontWeight:'800'}}>{p.nickname||`${p.manufacturer} ${p.model}`}{p.is_default?' · DEFAULT':''}</Text><Text style={{color:palette.muted,fontSize:13}}>{p.manufacturer} {p.model} · {p.field_strength_t}T</Text></Pressable>)}</View>:null}

    <View style={{height:1,backgroundColor:palette.line}}/><SectionTitle step="REQUIRED" title="Identify implant" detail="Search by manufacturer, product name, family, or model number. Device selection alone can open manufacturer MRI guidance."/>
    <SearchField value={deviceSearch} onChangeText={setDeviceSearch} placeholder="Example: 97810, InterStim, Percept PC" onSubmit={searchDevices}/><Pressable onPress={searchDevices} style={{alignSelf:'flex-start',backgroundColor:palette.brandSoft,paddingHorizontal:14,paddingVertical:9,borderRadius:radii.pill}}><Text style={{color:palette.brand,fontWeight:'800'}}>Search devices</Text></Pressable>
    {devices.map(item=><Pressable key={item.id} onPress={()=>{setDevice(item);setSelectedComponents([]);setComponents([]);setResult(null);}} style={{backgroundColor:device?.id===item.id?palette.brandSoft:palette.surface,borderWidth:1.5,borderColor:device?.id===item.id?palette.brand:palette.line,borderRadius:radii.md,padding:15,gap:3}}><Text style={{color:palette.text,fontSize:16,fontWeight:'800'}}>{item.manufacturer??'Manufacturer'} · {item.model??'Model'}</Text><Text style={{color:palette.muted,fontSize:13}}>{item.family??item.device_type??'Implantable device'}</Text></Pressable>)}

    {device?<><View style={{height:1,backgroundColor:palette.line}}/><SectionTitle step="OPTIONAL" title="Exact implanted components" detail="Skip this section when components are unknown. Add leads, electrodes, extensions, catheters, or accessories only when available for exact-system verification."/><SearchField value={componentSearch} onChangeText={setComponentSearch} placeholder="Search component model" onSubmit={searchComponents}/><Pressable onPress={searchComponents} style={{alignSelf:'flex-start',backgroundColor:palette.brandSoft,paddingHorizontal:14,paddingVertical:9,borderRadius:radii.pill}}><Text style={{color:palette.brand,fontWeight:'800'}}>Find components</Text></Pressable>{components.map(item=><Pressable key={item.id} onPress={()=>!selectedComponents.some(x=>x.id===item.id)&&setSelectedComponents(c=>[...c,{...item,slot:''}])} style={{backgroundColor:palette.surface,borderWidth:1,borderColor:palette.line,borderRadius:radii.md,padding:14}}><Text style={{color:palette.text,fontWeight:'800'}}>{item.model}</Text><Text style={{color:palette.muted,fontSize:13}}>{item.component_type}</Text></Pressable>)}{selectedComponents.map((item,i)=><View key={`${item.id}-${i}`} style={{backgroundColor:palette.brandSoft,borderRadius:radii.md,padding:14,gap:8}}><Text style={{color:palette.text,fontWeight:'800'}}>{item.model}</Text><TextInput value={item.slot} onChangeText={slot=>setSelectedComponents(c=>c.map((r,j)=>j===i?{...r,slot}:r))} placeholder="Slot (optional)" placeholderTextColor={palette.muted} returnKeyType="done" onSubmitEditing={Keyboard.dismiss} style={{backgroundColor:palette.surface,borderRadius:radii.sm,paddingHorizontal:12,height:44,color:palette.text}}/><Pressable onPress={()=>setSelectedComponents(c=>c.filter((_,j)=>j!==i))}><Text style={{color:palette.danger,fontSize:12,fontWeight:'800'}}>Remove component</Text></Pressable></View>)}</>:null}

    <View style={{height:1,backgroundColor:palette.line}}/><SectionTitle step="SCAN DETAILS" title="MRI scan details" detail="Use these to narrow manufacturer guidance. Exact components remain optional."/><TextInput value={scanRegion} onChangeText={setScanRegion} placeholder="Scan region" placeholderTextColor={palette.muted} returnKeyType="done" onSubmitEditing={Keyboard.dismiss} style={{backgroundColor:palette.surface,borderWidth:1,borderColor:palette.line,borderRadius:radii.md,paddingHorizontal:14,height:50,color:palette.text,fontSize:16}}/><TextInput value={serialNumber} onChangeText={setSerialNumber} autoCapitalize="characters" placeholder="Generator serial number (optional)" placeholderTextColor={palette.muted} returnKeyType="done" onSubmitEditing={Keyboard.dismiss} style={{backgroundColor:palette.surface,borderWidth:1,borderColor:palette.line,borderRadius:radii.md,paddingHorizontal:14,height:50,color:palette.text,fontSize:16}}/>
    <Pressable disabled={!device||busy} onPress={runCheck} style={{opacity:!device||busy?.45:1,backgroundColor:palette.brand,minHeight:58,borderRadius:radii.md,alignItems:'center',justifyContent:'center'}}>{busy?<ActivityIndicator color={palette.white}/>:<Text style={{color:palette.white,fontSize:17,fontWeight:'900'}}>{scanner&&selectedComponents.length?'Run Exact MRI QuickCheck':'View Manufacturer MRI Guidance'}</Text>}</Pressable>
    {result?<StatusCard tone={tone as any} eyebrow={result.display_status??'Result'} title={result.display_status??'QuickCheck result'} detail={result.decision??result.reason??result.next_action}><View style={{backgroundColor:palette.bg,borderRadius:radii.md,padding:12,gap:5}}><Text style={{color:palette.text,fontSize:13,fontWeight:'900'}}>{result.guidance_mode?'GUIDANCE MODE — NOT SCAN CLEARANCE':'MRI QUICKCHECK'}</Text>{result.guidance_mode?<Text style={{color:palette.muted,fontSize:13,lineHeight:19}}>Manufacturer guidance is shown without exact implanted-system verification. Add exact components when available before patient-specific clearance.</Text>:null}</View>{result.next_action?<Text style={{color:palette.text,fontSize:14,lineHeight:20,fontWeight:'700'}}>{result.next_action}</Text>:null}</StatusCard>:null}
    {Array.isArray(result?.conditions)?result.conditions.map((c:any)=><View key={c.id} style={{backgroundColor:palette.surface,borderRadius:radii.md,borderWidth:1,borderColor:c.matches_selected_scanner===false?palette.danger:palette.line,padding:15,gap:5}}><Text style={{color:palette.text,fontWeight:'900'}}>{c.field_strength_min_t===c.field_strength_max_t?`${c.field_strength_min_t}T`:`${c.field_strength_min_t??'?'}–${c.field_strength_max_t??'?'}T`} · {c.scan_region??'Manufacturer-defined region'}</Text>{c.max_whole_body_sar_w_kg!=null?<Text style={{color:palette.text}}>Whole-body SAR: ≤ {c.max_whole_body_sar_w_kg} W/kg</Text>:null}{c.max_b1_rms_ut!=null?<Text style={{color:palette.text}}>B1+rms: ≤ {c.max_b1_rms_ut} µT</Text>:null}{c.operating_mode?<Text style={{color:palette.text}}>Operating mode: {c.operating_mode}</Text>:null}{c.coil_requirements?<Text style={{color:palette.text}}>Coil: {c.coil_requirements}</Text>:null}{c.programming_requirements?<Text style={{color:palette.text}}>Programming: {c.programming_requirements}</Text>:null}{c.monitoring_requirements?<Text style={{color:palette.text}}>Monitoring: {c.monitoring_requirements}</Text>:null}{c.lead_requirements?<Text style={{color:palette.text}}>Components/leads: {c.lead_requirements}</Text>:null}{c.other_conditions?<Text style={{color:palette.text}}>Other: {c.other_conditions}</Text>:null}{c.source?.title?<Text style={{color:palette.muted,fontSize:12}}>Manufacturer source: {c.source.title}{c.source.document_version?` · ${c.source.document_version}`:''}</Text>:null}</View>):null}
  </ScrollView>;
}
