import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Keyboard, Linking, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { Image } from 'expo-image';
import * as Haptics from 'expo-haptics';
import { supabase } from '@/lib/supabase';
import { palette, radii } from '@/lib/theme';
import { StatusCard } from '@/components/status-card';

type ScannerOption = { id: string; manufacturer: string; model: string; field_strength_t: number };
type ScannerProfile = ScannerOption & { nickname?: string | null; is_default?: boolean; generic_scanner_model_id?: string | null };
type DeviceOption = { id: string; manufacturer?: string; model?: string; family?: string; device_type?: string; favorited_at?: string; last_used_at?: string; use_count?: number };
type ComponentOption = { id: string; model?: string; component_type?: string };
type SelectedComponent = ComponentOption & { slot: string };
type ChecklistItem = { key?: string; label?: string; requirement?: string; confirmed?: boolean };
type GuidanceCondition = { id:string; mr_status?:string; field_strength_min_t?:number|null; field_strength_max_t?:number|null; scan_region?:string|null; max_spatial_gradient_g_cm?:number|null; max_slew_rate_t_m_s?:number|null; max_whole_body_sar_w_kg?:number|null; max_head_sar_w_kg?:number|null; max_b1_rms_ut?:number|null; coil_requirements?:string|null; operating_mode?:string|null; positioning_requirements?:string|null; programming_requirements?:string|null; monitoring_requirements?:string|null; lead_requirements?:string|null; other_conditions?:string|null; matches_selected_scanner?:boolean|null; source?:{title?:string;source_url?:string;document_version?:string;effective_date?:string} };

const SCAN_REGIONS=['Head','Brain','C-spine','T-spine','L-spine','Chest','Abdomen','Pelvis','Upper extremity','Lower extremity','Full body'];
const DEVICE_CATEGORIES=[['Pain Pump','pain pump'],['SCS','SCS'],['DBS','DBS'],['SNM','SNM'],['VNS','VNS'],['Pacemaker','pacemaker'],['ICD / Defib','ICD'],['Loop Recorder','loop recorder']] as const;
const STANDARD_EXACT_BASES=new Set(['generator_specific_manufacturer_eligibility','manufacturer_verified_component_set','preverified_exact_system']);
function SectionTitle({step,title,detail}:{step:string;title:string;detail:string}){return <View style={{gap:4}}><Text style={{color:palette.brand,fontSize:12,fontWeight:'800',letterSpacing:.6}}>{step}</Text><Text style={{color:palette.text,fontSize:21,fontWeight:'800'}}>{title}</Text><Text style={{color:palette.muted,fontSize:14,lineHeight:20}}>{detail}</Text></View>}
function SearchField({value,onChangeText,placeholder,onSubmit}:{value:string;onChangeText:(v:string)=>void;placeholder:string;onSubmit:()=>void}){return <View style={{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:palette.surface,borderWidth:1,borderColor:palette.line,borderRadius:radii.md,paddingHorizontal:14}}><Image source="sf:magnifyingglass" style={{width:18,height:18}} tintColor={palette.muted}/><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={palette.muted} returnKeyType="search" autoCorrect autoCapitalize="none" onSubmitEditing={()=>{Keyboard.dismiss();onSubmit()}} style={{flex:1,height:50,color:palette.text,fontSize:16}}/></View>}
function Metric({label,value}:{label:string;value?:string|number|null}){if(value===undefined||value===null||value==='')return null;return <View style={{flex:1,minWidth:140,backgroundColor:palette.bg,borderRadius:radii.sm,padding:11,gap:2}}><Text style={{color:palette.muted,fontSize:11,fontWeight:'800'}}>{label}</Text><Text selectable style={{color:palette.text,fontSize:14,fontWeight:'800'}}>{String(value)}</Text></View>}
export default function QuickCheckScreen(){
 const[profiles,setProfiles]=useState<ScannerProfile[]>([]),[scanner,setScanner]=useState<ScannerOption|null>(null),[scannerProfileId,setScannerProfileId]=useState<string|null>(null),[showScannerPicker,setShowScannerPicker]=useState(false),[deviceSearch,setDeviceSearch]=useState(''),[devices,setDevices]=useState<DeviceOption[]>([]),[device,setDevice]=useState<DeviceOption|null>(null),[favorites,setFavorites]=useState<DeviceOption[]>([]),[recents,setRecents]=useState<DeviceOption[]>([]),[componentSearch,setComponentSearch]=useState(''),[components,setComponents]=useState<ComponentOption[]>([]),[selectedComponents,setSelectedComponents]=useState<SelectedComponent[]>([]),[scanRegion,setScanRegion]=useState('full body'),[showRegionPicker,setShowRegionPicker]=useState(false),[serialNumber,setSerialNumber]=useState(''),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[confirmations,setConfirmations]=useState<Record<string,boolean>>({});
 useEffect(()=>{(async()=>{const[{data:profileData},{data:favoriteData},{data:recentData}]=await Promise.all([supabase.rpc('quickcheck_list_scanner_profiles'),supabase.rpc('quickcheck_list_favorite_devices'),supabase.rpc('quickcheck_list_recent_devices',{p_limit:6})]);const rows=(profileData??[])as ScannerProfile[];setProfiles(rows);setFavorites((favoriteData??[])as DeviceOption[]);setRecents((recentData??[])as DeviceOption[]);const d=rows.find(x=>x.is_default);if(d){setScanner({id:d.generic_scanner_model_id||d.id,manufacturer:d.manufacturer,model:d.model,field_strength_t:d.field_strength_t});setScannerProfileId(d.id)}})()},[]);
 const favoriteIds=useMemo(()=>new Set(favorites.map(x=>x.id)),[favorites]);
 const recentUnpinned=useMemo(()=>recents.filter(x=>!favoriteIds.has(x.id)),[recents,favoriteIds]);
 const tone=useMemo(()=>result?.status==='safe'?'safe':result?.status==='conditional'||result?.status==='guidance'?'conditional':result?.status==='unsafe'||result?.status==='not_cleared'?'danger':'unknown',[result]);
 const conditions:GuidanceCondition[]=Array.isArray(result?.conditions)?result.conditions:[],checklist:ChecklistItem[]=Array.isArray(result?.condition_checklist)?result.condition_checklist:[];const allChecklistConfirmed=checklist.length>0&&checklist.every((x,i)=>confirmations[x.key||`item_${i}`]);
 async function refreshFavorites(){const{data,error}=await supabase.rpc('quickcheck_list_favorite_devices');if(!error)setFavorites((data??[])as DeviceOption[])}
 async function refreshRecents(){const{data,error}=await supabase.rpc('quickcheck_list_recent_devices',{p_limit:6});if(!error)setRecents((data??[])as DeviceOption[])}
 async function toggleFavorite(item:DeviceOption){const next=!favoriteIds.has(item.id);const{error}=await supabase.rpc('quickcheck_set_device_favorite',{p_device_id:item.id,p_favorite:next});if(error){setResult({status:'unknown',display_status:'PIN ERROR',decision:error.message});return}await Haptics.selectionAsync();await refreshFavorites()}
 async function doDeviceSearch(term:string){Keyboard.dismiss();setBusy(true);const{data,error}=await supabase.rpc('quickcheck_search_devices',{p_search:term.trim()});setBusy(false);if(error)return setResult({status:'unknown',display_status:'DEVICE SEARCH ERROR',decision:error.message});setDevices(((data??[])as DeviceOption[]).slice(0,20));}
 async function searchDevices(){await doDeviceSearch(deviceSearch)}
 async function quickCategory(term:string){setDeviceSearch(term);setDevice(null);setResult(null);setSelectedComponents([]);await Haptics.selectionAsync();await doDeviceSearch(term)}
 async function searchComponents(){Keyboard.dismiss();if(!device)return;setBusy(true);const{data,error}=await supabase.rpc('quickcheck_search_components',{p_device_id:device.id,p_search:componentSearch.trim()});setBusy(false);if(error)return setResult({status:'unknown',display_status:'COMPONENT SEARCH ERROR',decision:error.message});setComponents(((data??[])as ComponentOption[]).slice(0,30))}
 function chooseProfile(p:ScannerProfile){setScanner({id:p.generic_scanner_model_id||p.id,manufacturer:p.manufacturer,model:p.model,field_strength_t:p.field_strength_t});setScannerProfileId(p.id);setShowScannerPicker(false);setResult(null);setConfirmations({})}
 async function loadGuidance(selected:DeviceOption,selectedRegion=scanRegion){setBusy(true);setConfirmations({});const response=await supabase.rpc('quickcheck_get_device_guidance',{p_device_id:selected.id,p_scanner_strength_t:scanner?.field_strength_t??null,p_scan_region:selectedRegion.trim()||null});setBusy(false);setResult(response.error?{status:'unknown',display_status:'GUIDANCE ERROR',decision:response.error.message}:response.data)}
 async function selectDevice(item:DeviceOption){setDevice(item);setSelectedComponents([]);setComponents([]);await Promise.all([loadGuidance(item),supabase.rpc('quickcheck_mark_recent_device',{p_device_id:item.id})]);await refreshRecents()}
 async function runCheck(){Keyboard.dismiss();if(!device)return;setBusy(true);setConfirmations({});await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);let response:any;if(scanner&&selectedComponents.length){const args:any={p_device_id:device.id,p_components:selectedComponents.map((x,i)=>({component_id:x.id,slot:x.slot.trim()||`component_${i+1}`})),p_scanner_model_id:scanner.id,p_scanner_strength_t:scanner.field_strength_t,p_scan_region:scanRegion,p_generator_serial_number:serialNumber.trim()||null,p_implant_metadata:{}};if(scannerProfileId)args.p_scanner_profile_id=scannerProfileId;response=await supabase.rpc('quickcheck_run_exact_system_check_v3',args)}else response=await supabase.rpc('quickcheck_get_device_guidance',{p_device_id:device.id,p_scanner_strength_t:scanner?.field_strength_t??null,p_scan_region:scanRegion.trim()||null});setBusy(false);setResult(response.error?{status:'unknown',display_status:'QUICKCHECK ERROR',decision:response.error.message}:response.data)}
 async function verifyChecklist(){if(!device||!scanner||!allChecklistConfirmed||!STANDARD_EXACT_BASES.has(result?.verification_basis))return;setBusy(true);const response=await supabase.rpc('quickcheck_evaluate_condition_confirmation',{p_device_id:device.id,p_scanner_model_id:scanner.id,p_scanner_strength_t:scanner.field_strength_t,p_scan_region:scanRegion,p_confirmations:confirmations});setBusy(false);if(response.error)return setResult((c:any)=>({...c,decision:response.error.message}));setResult((c:any)=>({...c,...response.data,exact_system_verified:true}));await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)}
 const headline=result?.display_status||(result?.status==='guidance'?'MANUFACTURER MRI LABELING':'MRI LABELING RESULT');
 return <ScrollView contentInsetAdjustmentBehavior="automatic" keyboardDismissMode="interactive" keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:16,paddingBottom:60,gap:22}}>
 <SectionTitle step="OPTIONAL" title="Your scanner" detail="Your default saved scanner is selected automatically. Choose Scanner unknown when you only need the manufacturer's labeling."/>
 <Pressable onPress={()=>setShowScannerPicker(v=>!v)} style={{backgroundColor:palette.surface,borderWidth:1.5,borderColor:scanner?palette.brand:palette.line,borderRadius:radii.md,padding:15,flexDirection:'row',alignItems:'center',gap:12}}><Image source="sf:wave.3.right.circle.fill" style={{width:25,height:25}} tintColor={palette.brand}/><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'800',fontSize:16}}>{scanner?`${scanner.manufacturer} ${scanner.model}`:'Scanner unknown / guidelines only'}</Text><Text style={{color:palette.muted,fontSize:13}}>{scanner?`${scanner.field_strength_t}T · Saved scanner`:'Manufacturer labeling will still be shown'}</Text></View><Text style={{color:palette.brand,fontWeight:'900'}}>Change</Text></Pressable>
 {showScannerPicker?<View style={{gap:8}}><Pressable onPress={()=>{setScanner(null);setScannerProfileId(null);setShowScannerPicker(false);if(device)loadGuidance(device)}} style={{padding:14,borderRadius:radii.md,borderWidth:1,borderColor:palette.line,backgroundColor:palette.surface}}><Text style={{color:palette.text,fontWeight:'800'}}>Scanner unknown / guidelines only</Text></Pressable>{profiles.map(p=><Pressable key={p.id} onPress={()=>chooseProfile(p)} style={{padding:14,borderRadius:radii.md,borderWidth:1,borderColor:p.id===scannerProfileId?palette.brand:palette.line,backgroundColor:p.id===scannerProfileId?palette.brandSoft:palette.surface}}><Text style={{color:palette.text,fontWeight:'800'}}>{p.nickname||`${p.manufacturer} ${p.model}`}{p.is_default?' · DEFAULT':''}</Text><Text style={{color:palette.muted,fontSize:13}}>{p.manufacturer} {p.model} · {p.field_strength_t}T</Text></Pressable>)}</View>:null}
 <View style={{height:1,backgroundColor:palette.line}}/><SectionTitle step="REQUIRED" title="Identify implant" detail="Search by name, manufacturer, model, abbreviation, or common clinical term. Pin common implants or reopen recently used implants with one tap."/>
 {favorites.length>0?<View style={{gap:8}}><View style={{flexDirection:'row',alignItems:'center',gap:6}}><Image source="sf:pin.fill" style={{width:15,height:15}} tintColor={palette.brand}/><Text style={{color:palette.brand,fontSize:12,fontWeight:'900'}}>PINNED IMPLANTS</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:9,paddingRight:12}}>{favorites.map(item=><View key={item.id} style={{width:220,backgroundColor:palette.brandSoft,borderWidth:1,borderColor:palette.brand,borderRadius:radii.md,padding:12,gap:8}}><Pressable onPress={()=>selectDevice(item)} style={{gap:3}}><Text numberOfLines={1} style={{color:palette.text,fontWeight:'900'}}>{item.manufacturer??'Manufacturer'} · {item.model??'Model'}</Text><Text numberOfLines={1} style={{color:palette.muted,fontSize:12}}>{item.family??item.device_type??'Implantable device'}</Text></Pressable><Pressable onPress={()=>toggleFavorite(item)} style={{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:5}}><Image source="sf:pin.slash.fill" style={{width:14,height:14}} tintColor={palette.brand}/><Text style={{color:palette.brand,fontSize:12,fontWeight:'900'}}>Unpin</Text></Pressable></View>)}</ScrollView></View>:null}
 {recentUnpinned.length>0?<View style={{gap:8}}><View style={{flexDirection:'row',alignItems:'center',gap:6}}><Image source="sf:clock.arrow.circlepath" style={{width:16,height:16}} tintColor={palette.muted}/><Text style={{color:palette.muted,fontSize:12,fontWeight:'900'}}>RECENTLY USED</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:9,paddingRight:12}}>{recentUnpinned.map(item=><View key={item.id} style={{width:220,backgroundColor:palette.surface,borderWidth:1,borderColor:palette.line,borderRadius:radii.md,padding:12,gap:8}}><Pressable onPress={()=>selectDevice(item)} style={{gap:3}}><Text numberOfLines={1} style={{color:palette.text,fontWeight:'900'}}>{item.manufacturer??'Manufacturer'} · {item.model??'Model'}</Text><Text numberOfLines={1} style={{color:palette.muted,fontSize:12}}>{item.family??item.device_type??'Implantable device'}{item.use_count&&item.use_count>1?` · ${item.use_count} uses`:''}</Text></Pressable><Pressable onPress={()=>toggleFavorite(item)} style={{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:5}}><Image source="sf:pin" style={{width:14,height:14}} tintColor={palette.brand}/><Text style={{color:palette.brand,fontSize:12,fontWeight:'900'}}>Pin</Text></Pressable></View>)}</ScrollView></View>:null}
 <View style={{gap:8}}><Text style={{color:palette.muted,fontSize:12,fontWeight:'800'}}>QUICK CATEGORIES</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingRight:12}}>{DEVICE_CATEGORIES.map(([label,term])=><Pressable key={label} disabled={busy} onPress={()=>quickCategory(term)} style={{paddingHorizontal:13,paddingVertical:10,borderRadius:radii.pill,borderWidth:1,borderColor:deviceSearch.toLowerCase()===term.toLowerCase()?palette.brand:palette.line,backgroundColor:deviceSearch.toLowerCase()===term.toLowerCase()?palette.brandSoft:palette.surface}}><Text style={{color:deviceSearch.toLowerCase()===term.toLowerCase()?palette.brand:palette.text,fontWeight:'800'}}>{label}</Text></Pressable>)}</ScrollView></View>
 <SearchField value={deviceSearch} onChangeText={setDeviceSearch} placeholder="Pain pump, SCS, pacemaker, 97810, InterStim…" onSubmit={searchDevices}/><Pressable disabled={busy} onPress={searchDevices} style={{alignSelf:'flex-start',backgroundColor:palette.brandSoft,paddingHorizontal:14,paddingVertical:9,borderRadius:radii.pill}}><Text style={{color:palette.brand,fontWeight:'800'}}>Search devices</Text></Pressable>
 {busy?<ActivityIndicator color={palette.brand}/>:null}{devices.map(item=><View key={item.id} style={{backgroundColor:device?.id===item.id?palette.brandSoft:palette.surface,borderWidth:1.5,borderColor:device?.id===item.id?palette.brand:palette.line,borderRadius:radii.md,padding:13,flexDirection:'row',alignItems:'center',gap:10}}><Pressable onPress={()=>selectDevice(item)} style={{flex:1,gap:3,paddingVertical:2}}><Text style={{color:palette.text,fontSize:16,fontWeight:'800'}}>{item.manufacturer??'Manufacturer'} · {item.model??'Model'}</Text><Text style={{color:palette.muted,fontSize:13}}>{item.family??item.device_type??'Implantable device'}</Text></Pressable><Pressable accessibilityLabel={favoriteIds.has(item.id)?'Unpin implant':'Pin implant'} onPress={()=>toggleFavorite(item)} style={{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:favoriteIds.has(item.id)?palette.brand:palette.bg}}><Image source={favoriteIds.has(item.id)?'sf:pin.fill':'sf:pin'} style={{width:20,height:20}} tintColor={favoriteIds.has(item.id)?palette.white:palette.brand}/></Pressable></View>)}
 {result?<View style={{gap:12}}><View style={{backgroundColor:tone==='danger'?palette.danger:tone==='safe'?palette.safe:palette.surface,borderRadius:radii.lg,padding:18,gap:8,borderWidth:tone==='conditional'||tone==='unknown'?1:0,borderColor:tone==='conditional'?palette.conditional:palette.line}}><Text style={{color:tone==='danger'||tone==='safe'?palette.white:palette.muted,fontSize:12,fontWeight:'900'}}>{result.guidance_mode?'MANUFACTURER MRI LABELING':'EXACT SYSTEM QUICKCHECK'}</Text><Text selectable style={{color:tone==='danger'||tone==='safe'?palette.white:palette.text,fontSize:24,fontWeight:'900'}}>{headline}</Text><Text selectable style={{color:tone==='danger'||tone==='safe'?palette.white:palette.muted,fontSize:13,lineHeight:19}}>{result.decision??result.reason??result.next_action}</Text></View><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}><Metric label="Selected scanner" value={scanner?`${scanner.field_strength_t}T`:'Unknown'}/><Metric label="Scan region" value={scanRegion}/><Metric label="Verification" value={result.guidance_mode?'Manufacturer guidance':'Exact system'}/></View></View>:null}
 {conditions.map((c,i)=><View key={c.id||String(i)} style={{backgroundColor:palette.surface,borderRadius:radii.lg,borderWidth:1.5,borderColor:c.matches_selected_scanner===false?palette.danger:palette.line,padding:16,gap:10}}><Text style={{color:palette.brand,fontSize:11,fontWeight:'900'}}>MANUFACTURER CONDITION</Text><Text style={{color:palette.text,fontSize:19,fontWeight:'900'}}>{c.field_strength_min_t===c.field_strength_max_t?`${c.field_strength_min_t}T`:`${c.field_strength_min_t??'?'}–${c.field_strength_max_t??'?'}T`} · {c.scan_region??'Manufacturer-defined region'}</Text>{c.matches_selected_scanner===false?<Text style={{color:palette.danger,fontWeight:'900'}}>Does not match selected scanner/exam</Text>:null}<View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}><Metric label="Whole-body SAR" value={c.max_whole_body_sar_w_kg!=null?`≤ ${c.max_whole_body_sar_w_kg} W/kg`:null}/><Metric label="Head SAR" value={c.max_head_sar_w_kg!=null?`≤ ${c.max_head_sar_w_kg} W/kg`:null}/><Metric label="B1+rms" value={c.max_b1_rms_ut!=null?`≤ ${c.max_b1_rms_ut} µT`:null}/><Metric label="Spatial gradient" value={c.max_spatial_gradient_g_cm!=null?`${c.max_spatial_gradient_g_cm} G/cm`:null}/><Metric label="Slew rate" value={c.max_slew_rate_t_m_s!=null?`${c.max_slew_rate_t_m_s} T/m/s`:null}/></View>{[['Operating mode',c.operating_mode],['Coil',c.coil_requirements],['Positioning',c.positioning_requirements],['MRI mode/programming',c.programming_requirements],['Monitoring',c.monitoring_requirements],['Components/leads',c.lead_requirements],['Other conditions',c.other_conditions]].map(([l,v])=>v?<Text key={l as string} selectable style={{color:palette.text,fontSize:13,lineHeight:19}}><Text style={{fontWeight:'900'}}>{l}: </Text>{v}</Text>:null)}{c.source?.title?<View style={{gap:6,paddingTop:4,borderTopWidth:1,borderTopColor:palette.line}}><Text style={{color:palette.muted,fontSize:12}}>Manufacturer source: {c.source.title}{c.source.document_version?` · ${c.source.document_version}`:''}{c.source.effective_date?` · ${c.source.effective_date}`:''}</Text>{c.source.source_url?<Pressable onPress={()=>Linking.openURL(c.source!.source_url!)} style={{alignSelf:'flex-start',backgroundColor:palette.brand,paddingHorizontal:14,paddingVertical:10,borderRadius:radii.pill}}><Text style={{color:palette.white,fontWeight:'900'}}>Open Manufacturer MRI Instructions</Text></Pressable>:null}</View>:null}</View>)}
 {device?<><View style={{height:1,backgroundColor:palette.line}}/><SectionTitle step="OPTIONAL" title="Exact implanted components" detail="Manufacturer labeling remains visible if these are unknown. Add the complete implanted system when available to run exact-system verification."/><SearchField value={componentSearch} onChangeText={setComponentSearch} placeholder="Search lead, extension, electrode, catheter…" onSubmit={searchComponents}/><Pressable onPress={searchComponents} style={{alignSelf:'flex-start',backgroundColor:palette.brandSoft,paddingHorizontal:14,paddingVertical:9,borderRadius:radii.pill}}><Text style={{color:palette.brand,fontWeight:'800'}}>Find components</Text></Pressable>{components.map(item=><Pressable key={item.id} onPress={()=>!selectedComponents.some(x=>x.id===item.id)&&setSelectedComponents(c=>[...c,{...item,slot:''}])} style={{backgroundColor:palette.surface,borderWidth:1,borderColor:palette.line,borderRadius:radii.md,padding:14}}><Text style={{color:palette.text,fontWeight:'800'}}>{item.model}</Text><Text style={{color:palette.muted,fontSize:13}}>{item.component_type}</Text></Pressable>)}{selectedComponents.map((item,i)=><View key={`${item.id}-${i}`} style={{backgroundColor:palette.brandSoft,borderRadius:radii.md,padding:14,gap:8}}><Text style={{color:palette.text,fontWeight:'800'}}>{item.model}</Text><TextInput value={item.slot} onChangeText={slot=>setSelectedComponents(c=>c.map((r,j)=>j===i?{...r,slot}:r))} placeholder="Slot (optional)" placeholderTextColor={palette.muted} returnKeyType="done" onSubmitEditing={Keyboard.dismiss} style={{backgroundColor:palette.surface,borderRadius:radii.sm,paddingHorizontal:12,height:44,color:palette.text}}/><Pressable onPress={()=>setSelectedComponents(c=>c.filter((_,j)=>j!==i))}><Text style={{color:palette.danger,fontSize:12,fontWeight:'800'}}>Remove component</Text></Pressable></View>)}</>:null}
 <View style={{height:1,backgroundColor:palette.line}}/><SectionTitle step="SCAN DETAILS" title="MRI scan details" detail="Choose the exam region instead of typing it. This lets QuickCheck compare region restrictions consistently."/><Pressable onPress={()=>setShowRegionPicker(v=>!v)} style={{backgroundColor:palette.surface,borderWidth:1,borderColor:palette.line,borderRadius:radii.md,padding:14,flexDirection:'row',justifyContent:'space-between'}}><View><Text style={{color:palette.muted,fontSize:11,fontWeight:'800'}}>SCAN REGION</Text><Text style={{color:palette.text,fontSize:16,fontWeight:'800'}}>{scanRegion}</Text></View><Text style={{color:palette.brand,fontWeight:'900'}}>Choose</Text></Pressable>{showRegionPicker?<View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{SCAN_REGIONS.map(region=><Pressable key={region} onPress={()=>{const n=region.toLowerCase();setScanRegion(n);setShowRegionPicker(false);if(device)loadGuidance(device,n)}} style={{paddingHorizontal:12,paddingVertical:10,borderRadius:radii.pill,borderWidth:1,borderColor:scanRegion===region.toLowerCase()?palette.brand:palette.line,backgroundColor:scanRegion===region.toLowerCase()?palette.brandSoft:palette.surface}}><Text style={{color:scanRegion===region.toLowerCase()?palette.brand:palette.text,fontWeight:'800'}}>{region}</Text></Pressable>)}</View>:null}<TextInput value={serialNumber} onChangeText={setSerialNumber} autoCapitalize="characters" placeholder="Generator serial number (optional)" placeholderTextColor={palette.muted} returnKeyType="done" onSubmitEditing={Keyboard.dismiss} style={{backgroundColor:palette.surface,borderWidth:1,borderColor:palette.line,borderRadius:radii.md,paddingHorizontal:14,height:50,color:palette.text,fontSize:16}}/>
 <Pressable disabled={!device||busy} onPress={runCheck} style={{opacity:!device||busy?0.45:1,backgroundColor:palette.brand,minHeight:58,borderRadius:radii.md,alignItems:'center',justifyContent:'center'}}>{busy?<ActivityIndicator color={palette.white}/>:<Text style={{color:palette.white,fontSize:17,fontWeight:'900'}}>{scanner&&selectedComponents.length?'Run Exact MRI QuickCheck':'Refresh Manufacturer MRI Labeling'}</Text>}</Pressable>
 {checklist.length>0?<View style={{gap:10,backgroundColor:palette.surface,borderRadius:radii.lg,borderWidth:1,borderColor:palette.line,padding:16}}><Text style={{color:palette.brand,fontSize:11,fontWeight:'900'}}>CONDITIONS CHECKLIST</Text><Text style={{color:palette.text,fontSize:19,fontWeight:'900'}}>Confirm manufacturer requirements</Text>{checklist.map((item,i)=>{const key=item.key||`item_${i}`,checked=!!confirmations[key];return <Pressable key={key} onPress={()=>setConfirmations(c=>({...c,[key]:!checked}))} style={{flexDirection:'row',gap:11,padding:12,borderRadius:radii.md,backgroundColor:checked?palette.brandSoft:palette.bg}}><View style={{width:24,height:24,borderRadius:7,borderWidth:2,borderColor:checked?palette.brand:palette.line,backgroundColor:checked?palette.brand:palette.surface,alignItems:'center',justifyContent:'center'}}>{checked?<Text style={{color:palette.white,fontWeight:'900'}}>✓</Text>:null}</View><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'900'}}>{item.label||'Manufacturer condition'}</Text>{item.requirement?<Text selectable style={{color:palette.muted,fontSize:13,lineHeight:19}}>{item.requirement}</Text>:null}</View></Pressable>})}{allChecklistConfirmed&&!result?.guidance_mode&&STANDARD_EXACT_BASES.has(result?.verification_basis)?<Pressable disabled={busy} onPress={verifyChecklist} style={{backgroundColor:palette.safe,minHeight:52,borderRadius:radii.md,alignItems:'center',justifyContent:'center'}}><Text style={{color:palette.white,fontWeight:'900'}}>Verify All Confirmed Conditions</Text></Pressable>:null}</View>:null}
 {result&&!conditions.length?<StatusCard tone={tone as any} eyebrow={result.display_status??'Result'} title={result.display_status??'MRI result'} detail={result.decision??result.reason??result.next_action}/>:null}
 </ScrollView>;
}
